spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lol?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: beh73167380!

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

    data:
      web:
        pageable:
          default-page-size: 10

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  logging:
    level:
      org.hibernate.SQL: DEBUG
      # org.hibernate.type: trace
