parks.app.jwtSecret: qkrqudcks7
parks.app.jwtExpirationMs: 8640000

url: https://s3.ap-northeast-2.amazonaws.com/parkggupload
cloud:
  aws:
    credentials:
      accessKey: AKIAUAXUTEYSJYFQB2OB
      secretKey: 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
    s3:
      bucket: parkggupload
    region:
      static: ap-northeast-2
    stack:
      auto: false


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://loldb.cpzkshjlwu0y.ap-northeast-2.rds.amazonaws.com:3306/lol?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: park
    password: beh73167380!

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

    data:
      web:
        pageable:
          default-page-size: 10

  logging:
    level:
      org.hibernate.SQL: DEBUG
      # org.hibernate.type: trace
